### ISSUE TITLE
Make eclroot argument in ERT forward models optional

### ISSUE THREAD

**Issue by tnatt** [equinor/grid3d-maps#49]
Maps are often generated on exported RMS-data, hence the ERT forward model argument `"--eclroot" <ECLROOT>` should be optional.

**Comment by berland** [comment]
Optional arguments in ERT forward models are tricky, a solution to look at is the usage of `__NONE__` in 

https://github.com/equinor/semeio/blob/master/semeio/jobs/config_jobs/PYSCAL
and the accompanying file https://github.com/equinor/semeio/blob/master/semeio/jobs/scripts/fm_pyscal.py
